# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetworkCallExercise' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NetworkCallExercise
  pod 'Alamofire'
  pod 'NVActivityIndicatorView'
  pod 'SDWebImage'
  pod 'Rabbit-Swift'
  pod 'SwiftyJSON'

end
